version: "3"

services:
  ecommerce-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-backend-api
    container_name: ecommerce-backend-api
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ecommerce
      - KEYCLOAK_SERVER_JWK_URL=http://oauth-server:8080/realms/master/protocol/openid-connect/certs
    volumes:
      - ~/.gradle:/root/.gradle
    networks:
      - ecommnet
    depends_on:
      - db
      - oauth-server

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sritiman
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - ecommnet

  oauth-server:
    container_name: oauth-server
    image: quay.io/keycloak/keycloak:25.0.4
    command:
      - start-dev
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - ecommnet

volumes:
  my-db:
networks:
  ecommnet: