version: "3"

services:
  ecommerce-mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sritiman
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: