server:
  port: 8080
spring:
  datasource:
    url: ${MYSQL_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce}
    username: sritiman
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_JWK_URL:http://localhost:7080/realms/master/protocol/openid-connect/certs}

feign:
  client:
    config:
      payment-service:
        url: ${PAYMENT_SERVICE_URL:http://localhost:8081}

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 5s
      retryExceptions:
        - com.sritiman.ecommerce.ecommerceapplication.exceptions.payments.AccountNotFoundException


messaging:
  connection-information:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: "guest"
    password: "guest"
  exchange-information:
    order-create-exchange:
      name: "Buzz.Order.Create.Exchange"
      type: "fanout"
      queues:
        - name: "Buzz.Order.Create.Queue"